############################################################
# GENERAL APPLICATION SETTINGS
############################################################
spring.application.name=hotel-reservation-api
server.port=8080
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
# Swagger UI path: http://localhost:8080/swagger-ui/index.html



############################################################
# SPRING LOGGING SETTINGS
############################################################
# Write logs to the current directory
logging.file.path=.
logging.file.name=hotel-reservation-api.log
logging.level.dev.marioszocs.hotelreservationapi=debug




############################################################
# DEFAULT SPRING DATASOURCE SETTINGS for SQLite
############################################################
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:./data/hotel-reservation.db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false












